apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sky
  name: superset-oob
  labels:
    app: superset-oob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset-oob
  template:
    metadata:
      labels:
        app: superset-oob
    spec:
      containers:
      - name: superset-oob
        image: us-central1-docker.pkg.dev/cpl-dspm-l-sandbox-02/sky-dev-joey-andres/superset-oob
        ports:
        - containerPort: 8082
        env:
        # For production, it's recommended to use Kubernetes Secrets or ConfigMaps
        # to manage environment variables.
        - name: SUPERSET_HOST
          value: "http://superset:8088"
        - name: SUPERSET_USERNAME
          value: "admin"
        - name: SUPERSET_PASSWORD
          value: "admin"
        # Note: The local volumes from docker-compose.yml have been omitted.
        # In Kubernetes, you would typically build the application code into the docker image.
        # For persistent data, you should use PersistentVolumes and PersistentVolumeClaims.
