apiVersion: v1
kind: Service
metadata:
  namespace: sky
  name: sueprset-oob-service
  labels:
    io.kompose.service: superset
spec:
  selector:
    io.kompose.service: superset
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082